apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-v9
  namespace: bank-production-v9
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mysql-pv-v9