apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline7helm-pvc
  namespace: bank-production-v8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pipeline7helm-pv
  storageClassName: manual