apiVersion: v1
kind: Service
metadata:
  name: pipeline9-service
  namespace: bank-production-v9
spec:
  type: ClusterIP
  selector:
    app: pipeline9-app
  ports:
    - port: 80
      targetPort: 5000